# Default MQTT port (diubah ke 1884 untuk menghindari konflik Windows Service MQTT)
listener 1884
allow_anonymous true

# WebSockets port for Paho JS Client
listener 9001
protocol websockets
allow_anonymous true
